### ISSUE TITLE
Question about modifying themes.

### ISSUE THREAD

**Issue by cecoates** [tinytacoteam/dark-theme#1]
I'm having a lot of fun messing around with the CSS and tweaking the dark theme. 

![screenshot from 2017-01-18 18-51-52](https://cloud.githubusercontent.com/assets/10121835/22092235/ef328e36-ddc1-11e6-8387-36f7885b7f57.png)

But it only seems to work when I edit the files in the zazu-dark-theme directory. If I create my own, let's say zazu-orange-theme, and then update the .zazurc.json to match, Zazu won't load until it erases the directory I created. Then you see this:

![screenshot from 2017-01-18 21-07-56](https://cloud.githubusercontent.com/assets/10121835/22092316/6aef5c7a-ddc2-11e6-8ad8-5333b24faa64.png)

Am I missing something obvious?

**Comment by bayleedev** [comment]
Don't forget to submit it to the theme directory [:
